#!/bin/bash

rm -f ./thirdparty

myCurrentDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
: ${PoreScaleDir:=$myCurrentDIR} ; export PoreScaleDir
. $PoreScaleDir/bashrc

if [ -n "$1" ]; then 
	dataFiles=$1
else
	dataFiles="$(ls -d */ | sed 's/\///g')"
fi
	



for cas in $dataFiles
do
	if [ -L "$cas" ]; then
		 echo "rm $cas"
		 rm $cas
	elif [ -f $cas/Makefile ]; then
		echo "$cas:"	
		(cd $cas && make clean)
	elif [ -f $cas/makefile ]; then
		echo "$cas:"	
		(cd $cas && make clean)
	elif [ -f $cas/AllClean ]; then
		(cd $cas && ./AllClean)
	elif [ -d $cas ]; then
			echo " skipping $cas"	
	fi
done


rm -f  bin/*.d
rm -f  log log.AllMake
rm -rf build/*flow*/
rm -rf build/*extract*/
