#!/bin/bash



if ! [ -d thirdparty ]; then
	if [ -d ../thirdparty ]; then
		ln -s ../thirdparty ./
	fi
fi
if ! [ -d bin ]; then
	if [ -d ../bin/ ]; then
		ln -s ../bin ./
	fi
fi

SetedPoreScaleDir="$PoreScaleDir"

myCurrentDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
echo Running ${BASH_SOURCE[0]} on $myCurrentDIR  \{
if ! [ -n "$PoreScaleDir" ]; then
	echo " ";
	echo " PoreScale paths are not set"
	echo " please set them (preferably in your ~/.bashrc file) by adding in a new line:"
	echo " Press Cntrl+C to stop ";	echo " ";
	sleep 1
	echo "source $myCurrentDIR/bashrc"
	source $myCurrentDIR/bashrc
fi



if [ -n "$1" ]; then
    dataFiles=$1
else
	dataFiles="$(ls -d */ )"
fi



# needed to compile thirdparty libraries first 
for case in $dataFiles ; do
  if [ -f $case/makefile ]; then 
    echo ;  echo "* cd $case && make:"
	 (cd $case && make)
  fi
done

for case in $dataFiles ; do
  if [ -f $case/Makefile ]; then 
    echo ;  echo "* cd $case && make:"
	 (cd $case && make)
  elif [ -f $case/makefile ]; then echo
  else
    echo "* skipping $case"
  fi
done




echo "build directory: $myBinDir"
if ! [ -n "$SetedPoreScaleDir" ]; then
	echo " ";	echo " ";
	echo " variable PoreScaleDir is not permanently set"
	echo " please set in your ~/.bashrc file by adding new line:"
	echo "source $PoreScaleDir/bashrc"
	echo " ";
fi
