#!/bin/bash

echo "Run ./AllClean before running this script, when switching between Linux and Win"
export msCXX=x86_64-w64-mingw32-g++
#export msCFLAGS=-std=c++0x
export msLFLAGS=" -static -static-libstdc++ -static-libgcc "
export OPT=.exe
export preCC=x86_64-w64-mingw32-
sleep 1


SetedmsSrc="$msSrc"

myCurDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
echo Running ${BASH_SOURCE[0]} on $myCurDIR  \{
if ! [ -n "$msSrc" ]; then
	printf "\n PoreScale paths are not set\n please set them by running:\nsource $myCurDIR/bashrc\n"
	printf " Add this to your ~/.bashrc file to keep the settings.\n Press Cntrl+C to stop \n";
	sleep 1
	source $myCurDIR/bashrc
fi



if [ -n "$1" ]; then
    cases=$1
else
	cases="$(ls -d */ )"
fi



# needed to compile thirdparty libraries first 
for cas in $cases ; do
  if [ -f $cas/makefile ]; then 
    echo ;  echo "* cd $cas && make:"
	 (cd $cas && make)
  fi
done

for cas in $cases ; do
  if [ -f $cas/Makefile ]; then 
    echo ;  echo "* cd $cas && make:"
	 (cd $cas && make)
  elif [ -f $cas/makefile ]; then echo
  else
    echo "* skipping $cas"
  fi
done


echo "Note: run `make distclean` before running this script, when switching between Linux and Win"


echo "bin directory: $msBinDir"
if ! [ -n "$SetedmsSrc" ]; then
	printf "\n\n To install permanently, add the following line to your ~/.bashrc file:\n"
	printf "source $msSrc/bashrc\n\n"
fi

printf "check pnflow dependency:\nx86_64-w64-mingw32-objdump -p  $msBinDir/pnflow.exe    | grep 'DLL Name:'\n"
x86_64-w64-mingw32-objdump -p  $msBinDir/pnflow.exe    | grep 'DLL Name:'
